---
- name: After Install first steps
  become: yes
  hosts: debianos

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all packages on servers
    apt: upgrade=dist force_apt_get=yes

  - name: Install Midnight Commander
    apt: pkg=mc state=present

  - name: Install fail2ban package
    apt: pkg=fail2ban state=present
    when: ansible_distribution=='Debian' or ansible_distribution=='Ubuntu'

  - name: copy fail2ban local config to server
    copy: src=./configs/jail.090release.conf dest=/etc/fail2ban/jail.conf owner=root group=root mode=0644

  - name: restart fail2ban
    service: name=fail2ban state=restarted

  - name: reload fail2ban
    service: name=fail2ban state=reloaded
