---
- name: Getting data from routers
  hosts: mikrotik
  gather_facts: false

  tasks:

    - name: system command
      routeros_command:
        commands: /system routerboard print
      register: system_print

    - name: debug print
      debug: var=system_print.stdout_lines
