---
- name: OS version my servers
  hosts: all
  become: yes

  tasks:

  - debug:
     msg: "{{ansible_distribution}} {{ansible_distribution_version}}. Time:{{ansible_date_time.time}}{{ansible_date_time.tz_offset}}"